### ISSUE TITLE
Flatpak distribution tracking

### ISSUE THREAD

**Issue by Lunarequest** [shiftkey/desktop#553]
# Features

- [x] Login
- [x] Cloning/pulling https repositories 
- [x] Pushing to https repos
- [x] Cloning/pulling ssh repos. this does work but the password prompt shows up in the terminal if you don't have a gui manager for ssh
- [x] Changing theme works but requires a restart to apply
- [x] Editor integration (#554)
# Known issues
1. running github-desktop without the flatpak and then with the flatpak leads to github-desktop not being able to login into accounts.

**Comment by Lunarequest** [comment]
pr to flathub: https://github.com/flathub/flathub/pull/2417

**Comment by Lunarequest** [comment]
We now have the app on flathub https://github.com/flathub/io.github.shiftey.Desktop. it will reach the store front soon

**Comment by Croydon** [comment]
Thanks for pushing this! 🥳
